### ISSUE TITLE
Can not build with "Failed to load interface for ‘Sound.ProteaAudio’"

### ISSUE THREAD

**Issue by wkoiking** [ohri-anurag/sound-in-haskell#1]
I have tried building the app according to README. But it failed with the following error:

~~~
C:\Users\nao\sound-in-haskell\app\Main.hs:5:1: error:
    Failed to load interface for ‘Sound.ProteaAudio’
    Use -v to see a list of the files searched for.

C:\Users\nao\sound-in-haskell\app\Main.hs:8:1: error:
    Failed to load interface for ‘Data.ByteString’
    It is a member of the hidden package ‘bytestring-0.10.8.1’.
    Perhaps you need to add ‘bytestring’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.

--  While building custom Setup.hs for package sound-in-haskell-0.1.0.0 using:
      C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_1.24.2.0_ghc-8.2.2.exe --builddir=.stack-work\dist\ca59d0ab build lib:sound-in-haskell exe:sound-in-haskell-exe --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
~~~

I think the cause is the following line in .cabal file:
~~~
  other-modules:
      Paths_sound_in_haskell
~~~

Can you elaborate on how I can build this repo?

**Comment by ohri-anurag** [comment]
The issue might be that in the stack.yaml file, the resolver being used is lts-11.16. For VDU, we use lts-8.5. Maybe try changing the resolver, and then rebuild?

**Comment by ohri-anurag** [comment]
I tried changing the resolver to lts-8.5, and the build succeeded.

**Comment by wkoiking** [comment]
I already tried with both lts-11.15 and lts-8.5. Both of them fail.
I just cloned the repo and execute "stack ghci" or "stack build" command according to README.

As I explained above, the auto generated sound-in-haskell.cabal contains following line:

~~~
  other-modules:
      Paths_sound_in_haskell
~~~

I think stack can not not resolve the dependency with the above.
Please inform me what is contained in auto generated sound-in-haskell.cabal when you type `stack build` in your environment.

**Comment by wkoiking** [comment]
Also, please check whether the repo is immediately build-able after cloning in your environment.

**Comment by ohri-anurag** [comment]
The whole issue was that the cabal file was added to my .gitignore.

stack init command generates a new project and adds cabal file to .gitignore.

I have made some changes and added the modules to cabal file.

**Comment by wkoiking** [comment]
Now it is build-able. Thanks.
